---
- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ oh_my_zsh_path }}"
    update: yes

- name: Create configuration file
  copy:
    src={{ oh_my_zsh_rc_file_source_path | default( oh_my_zsh_path ~ "/templates/zshrc.zsh-template" ) }} dest={{ oh_my_zsh_rc_file_path }}
    remote_src={{ oh_my_zsh_rc_file_source_path is not defined | bool }}
    owner={{ oh_my_zsh_user }}
    group={{ oh_my_zsh_user }}
    mode=0644
