---

- name: "Combine specific with default variables"
  set_fact: {"oh_my_zsh_{{ item.user }}": "{{ vars | combine(item) }}"}
  with_dict: "{{ oh_my_zsh_users }}"

- include: oh-my-zsh.yml
  vars: {"{{ vars['oh_my_zsh_' ~ item.user] }}"}
  with_items: "{{ oh_my_zsh_users }}"