---
- include: oh-my-zsh.yml
  vars:
    user: "{{ item.user | default(item) }}"
    zsh_rc_file_path: "{{ item.zsh_rc_file_path | default(zsh_rc_file_path) }}"
    oh_my_zsh_path: "{{ item.oh_my_zsh_path | default(oh_my_zsh_path) }}"
    oh_my_zsh_rc_file_path: "{{ item.oh_my_zsh_rc_file_path | default(oh_my_zsh_rc_file_path) }}"
  with_items: "{{ oh_my_zsh_users }}"