---
- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ oh_my_zsh_path }}"
    update: yes
  become: yes
  become_user: "{{ user }}"

- name: Create configuration file
  copy:
    src: "{{ zsh_rc_file_path | default( oh_my_zsh_path ~ '/templates/zshrc.zsh-template' ) }}"
    dest: "{{ oh_my_zsh_rc_file_path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    remote_src: "{{ zsh_rc_file_path is defined }}"
    backup: yes
  become: yes
  become_user: "{{ user }}"

- name: Install oh-my-zsh themes
  git:
    repo: "{{ item.src }}"
    dest: "{{ oh_my_zsh_path ~ '/custom/themes' }}"
    update: yes
  become: yes
  become_user: "{{ user }}"
  with_items: "{{ oh_my_zsh_themes }}"


- name: Install oh-my-zsh plugins
  git:
    repo: "{{ item.src }}"
    dest: "{{ oh_my_zsh_path ~ '/custom/plugins' }}"
    update: yes
  become: yes
  become_user: "{{ user }}"
  with_items: "{{ oh_my_zsh_plugins }}"